### ISSUE TITLE
Create the association roadmap

### ISSUE THREAD

**Issue by toch** [brug-be/articles_of_association#9]
- [x] write statute
- [x] need at least 3 founders, we are 5 I think, need to check with everybody, and then chose the roles
- [x] make them review the statutes a last time
- [x] find an address for the association, it could be my house address
- [x] have the statute in FR and/or NL
- [x] publish the statute (it costs a little bit)
- [x] open a bank account, let's take the RG one?

**Comment by joren** [comment]
I'm still up for a little role in the founders. Will read up with the statutes this week. Promised!

**Comment by oana-sipos** [comment]
Hey,

I propose Christophe for president, as he was the initiator of all these.
For the rest, up as well for a little founder role.

Oana

On Sun, Mar 15, 2015 at 4:54 PM, Joren De Groof notifications@github.com
wrote:

> I'm still up for a little role in the founders. Will read up with the
> statutes this week. Promised!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/brug-be/statute/issues/9#issuecomment-81119163.

## 

Be: +32 485 462 660
Ro: +40 743 873 392

oanasipos.wordpress.com

**Comment by toch** [comment]
@ys and @hannesfostie what do you think?

**Comment by toch** [comment]
About the name, I realized that BRUG was also the name of the user group of brystol, belarus, brno, Białystok, Bangalore.

For that reason, I suggest something very simple and following the format of other Ruby Association: Ruby Belgium.

**Comment by toch** [comment]
FYI, it's possible to create it online via https://www.e-greffe.be/evzw/homepage
it costs 131,16€

**Comment by oana-sipos** [comment]
That sounds cool. Welcome to the country where you can do such things
online :D

Christophe, once we get to the step where you submit our statue & have to
pay, let me know so I can contribute to that amount.

Have a nice evening,
Oana

On Wed, Mar 25, 2015 at 6:22 PM, Christophe Philemotte <
notifications@github.com> wrote:

> FYI, it's possible to create it online via
> https://www.e-greffe.be/evzw/homepage
> it costs 131,16€
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/brug-be/statute/issues/9#issuecomment-86130583.

## 

Be: +32 485 462 660
Ro: +40 743 873 392

oanasipos.wordpress.com

**Comment by toch** [comment]
Quick recap from Slack:

Yannick and Hannes are ok to participate the board discussions and help when it's needed, but not to take a role needing "administration or financial" skills that they are not good at.

They are ok with the name.

I'm ready to take over any role. I have the experience in each of them. I'm ready to start as a president, I'm committed to build and grow it.

@oana-sipos and @joren would you be ok to take over one or another? treasurer or secretary?

As reminder, at the beginning, we'll run that the simplest and unformal we can. It's probably the best moment to take an official role as they won't be much to do at the beginning.

The first goal is to gather member and continue to organize/support event.

**Comment by joren** [comment]
sure, doesn't really matter which one, although 'treasurer' sounds pretty nice ;)

**Comment by toch** [comment]
I know you were into :money_with_wings: ;) Ok cool!

@oana-sipos would you be ok to be secretary?

**Comment by ys** [comment]
He is a captain

**Comment by oana-sipos** [comment]
@toch: Yes, that's ok

On Mon, Mar 30, 2015 at 2:08 PM, Christophe Philemotte <
notifications@github.com> wrote:

> I know you were into [image: :money_with_wings:] ;) Ok cool!
> 
> @oana-sipos https://github.com/oana-sipos would you be ok to be
> secretary?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/brug-be/statute/issues/9#issuecomment-87652082.

## 

Be: +32 485 462 660
Ro: +40 743 873 392

oanasipos.wordpress.com

**Comment by toch** [comment]
Ok quick recap:
- 5 founders, hannes, oana, yannick, joren, and me
- 3 board members: oana (secretary), joren (treasurer), me (president)
- my home address as HQ
- Ruby Belgium as a name

Still to do before creating the association:
- finalize the statute
- translate in FR or NL

I can translate it in FR next week. @joren and @hannesfostie could you do it for NL (it could be done later, as one lang is necessary to create the association)?

We're almost there ! :D

**Comment by toch** [comment]
Finally finished the final english version. I'm working on the French translation.

**Comment by toch** [comment]
@brug-be/members if one of you can check https://github.com/brug-be/statute/pull/10 thanks

**Comment by toch** [comment]
So, it's submitted. I'll contact the bank to transfer the RG bank account to the association.

**Comment by toch** [comment]
Just received from the administration:

> [...] Cette entreprise jouit dès à présent d'une personnalité juridique complète. [...]

**Comment by toch** [comment]
We can't directly transfer the bank account, we need to create a new one. I can take care of it, and eventually @joren needs also to be mandate holders. @joren do you want to take over this?

**Comment by toch** [comment]
@joren Keytrade offers free bank account also to NGO (to be confirmed). We just need to fill [that form](https://www.keytradebank.be/files/documentcenter/docsOpenASBL_fr.pdf).

**Comment by toch** [comment]
@joren Get answer from Keytrade:

```
Indeed the fees are the same for an ASBL as for a private person.

There are no fees to open or to close an an account for an ASBL/VZW. The current account and the savings account are free. There is no trading account related to this banking relationship.

! An ASBL cannot benefit from the 0.05 promo:
```

AS they provide great online bank account, I would go for KeyTrade as most of the classic banks doesn't provide free bank account for association.

**Comment by toch** [comment]
https://github.com/brug-be/rubybelgium-documents/issues/3

**Comment by cimm** [comment]
Nothing useful to add, just a quick note that "statue" in English translates  to "Articles of association". Yes, it doesn't sound as fun but it's the right term. ;) Guess I should open a pull request for that one.

**Comment by toch** [comment]
@cimm you mean `statute` right?

I think the last think to do is a NL version
